id: containers_docker_basics
category: docker
level: beginner
title: Docker Basics
description: Discover the fundamental concepts of Docker and containers

questions:
  - id: q1
    question: Which command lists all running Docker containers?
    options:
      - docker ps
      - docker list
      - docker containers
      - docker show
    explanation: The 'docker ps' command displays the list of running containers. To see all containers (including stopped ones), use 'docker ps -a'.
    source: "Docker Documentation - https://docs.docker.com/engine/reference/commandline/ps/"
    correct_answer: 0

  - id: q2
    question: What does the 'docker pull' command do?
    options:
      - Downloads an image from a registry
      - Starts a container
      - Stops a container
      - Removes an image
    explanation: The 'docker pull' command downloads an image from a registry (Docker Hub by default) to your local machine.
    source: "Docker Documentation - https://docs.docker.com/engine/reference/commandline/pull/"
    correct_answer: 0

  - id: q3
    question: What is the difference between a Docker image and a Docker container?
    options:
      - The image is a read-only template, the container is a running instance
      - The image is larger than the container
      - The container is a template, the image is an instance
      - There is no difference
    explanation: A Docker image is a read-only template containing instructions to create a container. A container is a running instance of an image, with its own filesystem, network, and isolated processes.
    source: "Docker Documentation - https://docs.docker.com/get-started/overview/"
    correct_answer: 0

  - id: q4
    question: What does the -d mean in the 'docker run -d' command?
    options:
      - Runs the container in detached mode (background)
      - Deletes the container after it stops
      - Enables debug mode
      - Disables logging
    explanation: The -d (detach) option runs the container in the background. The container continues to run but is not attached to your current terminal.
    source: "Docker Documentation - https://docs.docker.com/engine/reference/run/#detached--d"
    correct_answer: 0