title: Ansible Advanced Concepts
description: Test your intermediate knowledge of Ansible automation
category: ansible
level: intermediate
questions:
  - id: ansible_i1
    question: What is an Ansible handler and when is it triggered?
    options:
      - A task that runs only when notified by another task after a change
      - A task that runs automatically at the start of a playbook
      - A task that handles errors in playbooks
      - A task that manages host connections
    correct_answer: 0
    explanation: A handler is a task that only runs when notified by another task that has made a change. They are commonly used for restarting services or triggering other actions when configurations change.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html

  - id: ansible_i2
    question: What is the purpose of the 'when' statement in Ansible?
    options:
      - To implement conditional execution of tasks
      - To specify when a playbook should run
      - To set task timeout
      - To schedule periodic tasks
    correct_answer: 0
    explanation: The 'when' statement is used for conditional execution of tasks based on variables, facts, or previous task results.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html

  - id: ansible_i3
    question: How do you handle sensitive data in Ansible?
    options:
      - Using Ansible Vault
      - Using environment variables only
      - Using plain text variables
      - Using external databases
    correct_answer: 0
    explanation: Ansible Vault is used to encrypt sensitive data such as passwords, keys, or sensitive variables, allowing secure storage in version control.
    source: https://docs.ansible.com/ansible/latest/vault_guide/index.html

  - id: ansible_i4
    question: What is the purpose of 'gather_facts' in a playbook?
    options:
      - To collect system information about target hosts
      - To gather playbook statistics
      - To collect network information only
      - To gather user information
    correct_answer: 0
    explanation: gather_facts is used to collect system information (facts) about target hosts, including OS details, IP addresses, hardware info, etc.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html

  - id: ansible_i5
    question: What is an Ansible Galaxy?
    options:
      - A repository for sharing and downloading Ansible roles
      - A monitoring tool for Ansible
      - A testing framework
      - A deployment tool
    correct_answer: 0
    explanation: Ansible Galaxy is a repository for sharing, downloading, and managing Ansible roles created by the Ansible community.
    source: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html

  - id: ansible_i6
    question: What is the purpose of 'block' in Ansible playbooks?
    options:
      - To group multiple tasks and handle errors
      - To create a new variable scope
      - To define a new play
      - To create a loop
    correct_answer: 0
    explanation: Blocks allow you to group related tasks together and handle errors for the entire group of tasks using rescue and always sections.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_blocks.html

  - id: ansible_i7
    question: How can you handle different operating systems in Ansible?
    options:
      - Using when conditions with ansible_facts['os_family']
      - Using separate playbooks for each OS
      - Using different inventory files
      - Using OS-specific modules only
    correct_answer: 0
    explanation: You can use conditional statements with ansible_facts['os_family'] or ansible_facts['distribution'] to execute tasks based on the target system's OS.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_conditionals.html

  - id: ansible_i8
    question: What is the purpose of 'strategy' in Ansible playbooks?
    options:
      - To control how plays are executed across hosts
      - To define deployment strategies
      - To manage variable precedence
      - To handle task failures
    correct_answer: 0
    explanation: Strategy controls how Ansible executes tasks across hosts (linear, free, or debug), affecting parallelism and execution order.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_strategies.html

  - id: ansible_i9
    question: What is an Ansible lookup plugin?
    options:
      - A plugin to fetch data from external sources
      - A plugin to look up module documentation
      - A plugin to search playbooks
      - A plugin to find roles
    correct_answer: 0
    explanation: Lookup plugins are used to access data from external sources like files, databases, or key-value stores during playbook execution.
    source: https://docs.ansible.com/ansible/latest/plugins/lookup.html

  - id: ansible_i10
    question: What is the purpose of 'tags' in Ansible playbooks?
    options:
      - To selectively execute specific parts of a playbook
      - To label playbook versions
      - To categorize variables
      - To mark deprecated tasks
    correct_answer: 0
    explanation: Tags allow you to selectively execute or skip specific parts of a playbook by marking tasks, roles, or plays with tags.
    source: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html 